name = "yonsei-photo-cleanup"
main = "worker.mjs"
workers_dev = false
preview_urls = false
send_metrics = false
compatibility_date = "2026-09-26"
[triggers]
crons = ["*/10 * * * *"]
[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "yonsei-studio-photos"

[observability]
enabled = true
