import assert from 'node:assert/strict';import {gallery,cleanup} from '../lib/gallery.mjs';import {createPrintServer} from '../mac-print/server.mjs';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
const store=new Map();let sequence=0;const bucket={async put(k,v,o={}){if(o.onlyIf?.etagMatches&&store.get(k)?.etag!==o.onlyIf.etagMatches)return null;const entry={v,o,etag:String(++sequence)};store.set(k,entry);return entry;},async get(k){const e=store.get(k);return e?{etag:e.etag,text:async()=>String(e.v),body:e.v,httpMetadata:e.o.httpMetadata}:null;},async delete(keys){for(const k of keys)store.delete(k);},async list(){return{objects:[...store].map(([key,e])=>({key,customMetadata:e.o.customMetadata})),truncated:false};}};
const env={CLEANUP_ENABLED:'1',KIOSK_SECRET:'cloud-test-secret-at-least-32-characters',PHOTOS:bucket};const origin='https://askive.pages.dev';let cookie='';const call=(path,method='GET',body,headers={})=>gallery(new Request(origin+'/api/gallery/'+path,{method,body,headers:{Origin:origin,Cookie:cookie,...headers}}),env);
const login=await call('unlock','POST',JSON.stringify({code:env.KIOSK_SECRET}));cookie=login.headers.get('set-cookie').split(';')[0];
const jpeg=Buffer.from([255,216,255,192,0,17,8,6,240,4,176,3,1,17,0,2,17,0,3,17,0,255,217]);
const files=qr=>{const f=new FormData();for(const n of qr?[0,1,2,3,4,5,6,7,8,9]:[8])f.append(String(n),new Blob([jpeg],{type:'image/jpeg'}),'photo.jpg');return f;};
const a=await(await call('albums','POST',JSON.stringify({printOnly:true,consent:false}))).json();assert.equal((await call('albums/'+a.id,'PUT',files(false))).status,200);assert.equal([...store.keys()].filter(k=>k.startsWith(a.id+'/')).length,2);assert.equal((await call('albums/'+a.id)).status,403);assert.equal((await call('albums/'+a.id+'/8')).status,403);assert.equal((await call('albums/'+a.id+'/0')).status,403);
const client='a'.repeat(48),other='b'.repeat(48);const bridge=(path,method='GET',who=client)=>gallery(new Request(origin+'/api/gallery/print-jobs'+path,{method,headers:{Authorization:'Bearer '+env.KIOSK_SECRET,'X-Print-Client':who}}),env);
assert.equal((await(await bridge('')).json()).jobs.length,0);assert.equal((await call('albums/'+a.id+'/print','POST')).status,200);assert.equal((await(await bridge('')).json()).jobs.length,1);
const races=await Promise.all([bridge('/'+a.id+'/claim','POST'),bridge('/'+a.id+'/claim','POST',other)]);assert.deepEqual(races.map(r=>r.status).sort(),[200,409]);assert.equal((await bridge('/'+a.id+'/image','GET',other)).status,403);assert.equal((await bridge('/'+a.id+'/image')).status,200);assert.equal((await bridge('/'+a.id+'/received','POST')).status,200);assert.equal((await(await bridge('')).json()).jobs.length,0);
const q=await(await call('albums','POST',JSON.stringify({printOnly:true,consent:false}))).json();assert.equal((await call('albums/'+q.id+'/qr','POST',JSON.stringify({consent:true,policyVersion:'2026-09-26-qr-v1'}))).status,200);assert.equal((await call('albums/'+q.id,'PUT',files(true))).status,200);assert.equal([...store.keys()].filter(k=>k.startsWith(q.id+'/')).length,11);assert.equal((await call('albums/'+q.id)).status,200);assert.equal((await call('albums/'+q.id+'/0')).status,200);assert.equal((await call('albums/'+q.id+'/9')).status,403);assert.equal((await call('albums/'+q.id+'/print','POST')).status,200);
const nativeFetch=globalThis.fetch;globalThis.fetch=async(url,options)=>String(url).startsWith(origin+'/api/gallery/print-jobs')?gallery(new Request(url,options),env):nativeFetch(url,options);
const dir=await mkdtemp(join(tmpdir(),'cloud-print-test-'));const run=async(file)=>file.endsWith('lpstat')?'device for CP1500: ippusb://test\n':file.endsWith('lpoptions')?'PageSize: Postcard.Fullbleed':'';const server=createPrintServer({directory:dir,run});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
try{const connect=await fetch(base+'/admin/cloud',{method:'POST',headers:{Origin:base,'X-Yonsei-Admin':'1','Content-Type':'application/json'},body:JSON.stringify({code:env.KIOSK_SECRET})});assert.equal(connect.status,200);let state;for(let n=0;n<40;n++){state=await(await fetch(base+'/admin/state')).json();if(state.jobs.length)break;await new Promise(r=>setTimeout(r,25));}assert.equal(state.jobs.length,1);assert.equal(state.jobs[0].cloudId,q.id);assert.equal(state.jobs[0].state,'waiting');assert.ok(!JSON.stringify(state).includes(env.KIOSK_SECRET));await cleanup(bucket,Date.now()+86401000);assert.equal(store.size,0);console.log('PASS: no-QR private completion only, QR eight extras, private print file, 24-hour deletion, atomic multi-laptop claim, automatic authenticated laptop receipt. No physical print.');}finally{await new Promise(r=>server.close(r));globalThis.fetch=nativeFetch;await rm(dir,{recursive:true,force:true});}
