import {chromium} from 'playwright';
import {createApp} from '../server.mjs';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const app=createApp({});await new Promise(r=>app.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
try{
const p=await browser.newPage({viewport:{width:1024,height:768},permissions:['camera']});
await p.route('**/app.js',async route=>{const s=await readFile('dist/app.js','utf8');await route.fulfill({contentType:'text/javascript',body:s+`\nwindow.verifyWide=async()=>{phase='shoot';edition='special';cutCount=4;await startCamera();const settings=stream.getVideoTracks()[0].getSettings();const photo=document.createElement('canvas');photo.width=video.videoWidth;photo.height=video.videoHeight;const pc=photo.getContext('2d');pc.fillStyle='#ff0000';pc.fillRect(0,0,photo.width,photo.height);shotSession={photos:[photo],taken:0};chosen=[0,0,0,0];$('photo-filter').value='original';const reports=[];for(const frame of frames.filter(f=>f.id.endsWith('-wide'))){selected=prepareFrame(frame,await loadImage(frame.src));$('overlay').src=frame.src;const size=outputSize(selected,4);for(let i=0;i<4;i++){shotSession.taken=i;showShotPreview();const v=video.getBoundingClientRect(),o=$('overlay').getBoundingClientRect(),slot=size.slots[i];const sx=o.x+slot.x/size.width*o.width,sy=o.y+slot.y/size.height*o.height; if(Math.abs(v.x-sx)>1||Math.abs(v.y-sy)>1||Math.abs(v.width-slot.w/size.width*o.width)>1||Math.abs(v.height-slot.h/size.height*o.height)>1)throw new Error(frame.id+' preview misalignment');}const out=document.createElement('canvas');composeSelection(out);const c=out.getContext('2d'),mask=document.createElement('canvas');mask.width=out.width;mask.height=out.height;const m=mask.getContext('2d');m.drawImage(selected.img,0,0);const a=m.getImageData(0,0,out.width,out.height).data,d=c.getImageData(0,0,out.width,out.height).data;let holes=0;for(let i=0;i<a.length;i+=4)if(a[i+3]===0){holes++;if(d[i]!==255||d[i+1]!==0||d[i+2]!==0)throw new Error(frame.id+' uncovered pixel '+i);}reports.push({id:frame.id,holes});}stopStream();return{settings,source:[photo.width,photo.height],reports};};`});});
await p.goto(`http://127.0.0.1:${app.address().port}`);await p.waitForFunction(()=>window.verifyWide);await p.waitForTimeout(500);const r=await p.evaluate(()=>verifyWide());assert.ok(Math.abs(r.source[0]/r.source[1]-4/3)<.01);assert.equal(r.reports.length,4);assert.ok(r.reports.every(f=>f.holes>100000));console.log(JSON.stringify(r));console.log('PASS: 4:3 camera source, all 16 landscape preview slots aligned, every transparent output pixel filled.');
}finally{await browser.close();await new Promise(r=>app.close(r));}
