import assert from 'node:assert/strict';import {gallery} from '../lib/gallery.mjs';import {createPrintServer} from '../mac-print/server.mjs';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
const store=new Map();let n=0;const env={CLEANUP_ENABLED:'1',KIOSK_SECRET:'relay-test-secret-at-least-32-characters',PHOTOS:{async put(k,v,o={}){if(o.onlyIf?.etagMatches&&store.get(k)?.etag!==o.onlyIf.etagMatches)return null;const a={v,o,etag:String(++n)};store.set(k,a);return a;},async get(k){const a=store.get(k);return a?{etag:a.etag,text:async()=>String(a.v),body:a.v,httpMetadata:a.o.httpMetadata}:null;},async delete(ks){for(const k of ks)store.delete(k);},async list(){return {objects:[...store].map(([key,a])=>({key,customMetadata:a.o.customMetadata})),truncated:false};}}};
const origin='https://askive.pages.dev';let cookie='';const call=(p,method='GET',data,headers={})=>gallery(new Request(origin+'/api/gallery/'+p,{method,headers:{Origin:origin,Cookie:cookie,...headers},...(data?{body:data instanceof FormData?data:JSON.stringify(data)}:{})}),env);
assert.equal((await call('printer-relay/devices')).status,401);assert.equal((await call('printer-relay/register','POST',{password:'bad'})).status,403);
const machine=await(await call('printer-relay/register','POST',{password:'0691',name:'Test Mac'})).json();assert.match(machine.token,/^[a-f0-9]{48}$/);const stored=JSON.parse(store.get('_print_devices/'+machine.id).v);assert.ok(!JSON.stringify(stored).includes(machine.token));assert.ok(stored.expiresAt-Date.now()>29*86400000);
const login=await call('unlock','POST',{code:env.KIOSK_SECRET});cookie=login.headers.get('set-cookie').split(';')[0];const printedLogin=await call('print-login','POST',{password:'0691'});cookie+='; '+printedLogin.headers.get('set-cookie').split(';')[0];const album=await(await call('albums','POST',{printOnly:true,consent:false})).json();const jpeg=Buffer.from([255,216,255,192,0,17,8,6,240,4,176,3,1,17,0,2,17,0,3,17,0,255,217]);const form=new FormData();form.append('8',new Blob([jpeg],{type:'image/jpeg'}),'complete.jpg');await call('albums/'+album.id,'PUT',form);await call('albums/'+album.id+'/print','POST');const m=JSON.parse(store.get(album.id+'/meta').v);assert.ok(m.expiresAt-Date.now()<=86400000);
const auth={Authorization:'Bearer '+machine.token};assert.equal((await call('printer-relay/'+machine.id+'/heartbeat','POST',{printers:[{name:'CP1500',usb:true}]},auth)).status,200);
const d=await(await call('printer-relay/devices')).json();assert.equal(d.devices.length,1);const request={album:album.id,device:machine.id,printer:'CP1500',copies:2,scale:94,rotation:90};const concurrent=await Promise.all([call('printer-relay/submit','POST',request),call('printer-relay/submit','POST',request)]);assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,409]);assert.equal((await call('printer-relay/'+machine.id+'/commands','GET',null,{Authorization:'Bearer '+'f'.repeat(48)})).status,401);
const oldFetch=globalThis.fetch;let retryResult=true;globalThis.fetch=async(url,options)=>{if(String(url).startsWith(origin+'/api/gallery/')){if(String(url).endsWith('/result')&&retryResult){retryResult=false;return new Response('{}',{status:503});}return gallery(new Request(url,options),env);}return oldFetch(url,options);};const dir=await mkdtemp(join(tmpdir(),'relay-helper-test-'));await writeFile(join(dir,'relay.json'),JSON.stringify(machine));const prints=[];const run=async(file,args)=>{if(file.endsWith('lpstat'))return 'device for CP1500: ippusb://test\n';if(file.endsWith('lpoptions'))return 'PageSize: Postcard.Fullbleed';if(file.endsWith('/lp')){prints.push(args);return 'request id is CP1500-1';}throw Error('Unexpected command');};const server=createPrintServer({directory:dir,run});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{let meta;for(let i=0;i<160;i++){meta=JSON.parse(store.get(album.id+'/meta').v);if(meta.webPrintState==='submitted')break;await new Promise(r=>setTimeout(r,50));}assert.equal(meta.webPrintState,'submitted');assert.equal(prints.length,1);assert.ok(prints[0].includes('2'));const devices=await(await call('printer-relay/devices')).json();assert.equal(devices.devices[0].printers[0].name,'CP1500');console.log('PASS: HTTPS printer listing, 30-day metadata credentials, unchanged 24-hour photos, concurrent request guard, direct helper print, lost-result retry without duplicate printing. No physical print.');}finally{await new Promise(r=>server.close(r));globalThis.fetch=oldFetch;await rm(dir,{recursive:true,force:true});}
