import {existsSync,readFileSync,writeFileSync,readdirSync,unlinkSync} from 'node:fs';import {join} from 'node:path';
export function startPrinterRelay({directory,port,token,printers}){
 const config=join(directory,'relay.json');if(!existsSync(config))return()=>{};const connection=JSON.parse(readFileSync(config));if(!/^[a-f0-9]{48}$/.test(connection.id||'')||!/^[a-f0-9]{48}$/.test(connection.token||''))return()=>{};
 let busy=false,stopped=false,timer;let pollMs=15000;const remote=async(path,method='GET',body)=>{const r=await fetch(`https://askive.pages.dev/api/gallery/printer-relay/${connection.id}/${path}`,{method,headers:{Authorization:'Bearer '+connection.token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('인쇄 클라우드 응답 '+r.status);return r;};const local=async(path,body,type='application/json')=>{const base='http://127.0.0.1:'+port;const r=await fetch(base+path,{method:'POST',headers:{Origin:base,'X-Yonsei-Admin':'1',Authorization:'Bearer '+token,'Content-Type':type},body:type==='application/json'?JSON.stringify(body):body,signal:AbortSignal.timeout(30000)});const data=await r.json();if(!r.ok)throw Error(data.error||'인쇄 도우미 오류');return data;};
 async function tick(){if(busy||stopped)return;busy=true;try{for(const name of readdirSync(directory).filter(n=>/^relay-[a-f0-9]{48}\.json$/.test(n))){try{if(JSON.parse(readFileSync(join(directory,name))).at<Date.now()-86400000)unlinkSync(join(directory,name));}catch{}}
 const current=await printers();let lastReport=Date.now();const heartbeat=await(await remote('heartbeat','POST',{printers:current.map(p=>({name:p.name,usb:p.uri.startsWith('ippusb:')||p.uri.startsWith('usb:')}))})).json();pollMs=heartbeat.active?4000:15000;if(!heartbeat.active)return;const {commands}=await(await remote('commands')).json();
 for(const command of commands){if(stopped)break;if(Date.now()-lastReport>10000){await remote('heartbeat','POST',{printers:current.map(p=>({name:p.name,usb:p.uri.startsWith('ippusb:')||p.uri.startsWith('usb:')}))});lastReport=Date.now();}if(!/^[a-f0-9]{48}$/.test(command.id)||!/^[a-f0-9]{48}$/.test(command.album))continue;const receipt=join(directory,'relay-'+command.id+'.json'),identity={album:command.album,command:command.id};await remote('claim','POST',identity);let record=existsSync(receipt)?JSON.parse(readFileSync(receipt)):null;
 if(record?.state==='sending'){record.state='uncertain';writeFileSync(receipt,JSON.stringify(record),{mode:0o600});}
 if(!record){const response=await remote(`image?album=${command.album}&command=${command.id}`),reader=response.body.getReader(),chunks=[];let total=0;while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>8500000){await reader.cancel();throw Error('인쇄 사진 용량 초과');}chunks.push(Buffer.from(value));}const file=Buffer.concat(chunks);const imported=await local('/admin/import',file,'image/jpeg');record={state:'sending',at:Date.now()};writeFileSync(receipt,JSON.stringify(record),{mode:0o600});try{const result=await local(`/admin/jobs/${imported.id}/print`,{printer:command.printer,copies:command.copies,scale:command.scale,rotation:command.rotation,reprint:imported.state!=='waiting',expectedAttempt:imported.attempt});record.state=result.state==='submitted'?'submitted':'uncertain';}catch{record.state='uncertain';}writeFileSync(receipt,JSON.stringify(record),{mode:0o600});}
 await remote('result','POST',{...identity,state:record.state});
 }
 }catch{}finally{busy=false;if(!stopped){timer=setTimeout(()=>void tick(),pollMs);timer.unref();}}}
 void tick();return()=>{stopped=true;clearTimeout(timer);};
}
