const enc=new TextEncoder(),hex=a=>Array.from(a,v=>v.toString(16).padStart(2,'0')).join(''),random=()=>hex(crypto.getRandomValues(new Uint8Array(24))),hash=async v=>hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(v))));
const reply=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store, private','X-Content-Type-Options':'nosniff'}}),key=id=>'_print_devices/'+id,opts=m=>({customMetadata:{expiresAt:String(m.expiresAt)}});const attempts=new Map();
async function body(req){const reader=req.body?.getReader();if(!reader)return {};let total=0;const parts=[];while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>8192){await reader.cancel();throw Error();}parts.push(value);}const bytes=new Uint8Array(total);let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.length;}return JSON.parse(new TextDecoder().decode(bytes)||'{}');}
async function albums(b){const keys=[];let cursor;do{const p=await b.list({limit:1000,cursor});for(const item of p.objects)if(/^[a-f0-9]{48}\/meta$/.test(item.key))keys.push(item.key);cursor=p.truncated?p.cursor:undefined;}while(cursor);const records=[];for(let i=0;i<keys.length;i+=20){const batch=await Promise.all(keys.slice(i,i+20).map(async key=>{const object=await b.get(key);return object?{id:key.split('/')[0],object,meta:JSON.parse(await object.text())}:null;}));records.push(...batch.filter(Boolean));}return records;}
export async function printerRelay(req,env,{loggedIn,verifyPassword}){
 const path=new URL(req.url).pathname.slice('/api/gallery/printer-relay'.length),now=Date.now(),b=env.PHOTOS;
 try{
 if(path==='/register'&&req.method==='POST'){
  const ip=req.headers.get('cf-connecting-ip')||'local';for(const [k,v] of attempts)if(now-v.at>300000)attempts.delete(k);const a=attempts.get(ip)||{at:now,n:0};if(a.n>=8)return reply({error:'잠시 후 다시 연결해 주세요.'},429);
  const d=await body(req);if(!await verifyPassword(d.password)){a.n++;attempts.set(ip,a);return reply({error:'인쇄관리 비밀번호를 확인해 주세요.'},403);}attempts.delete(ip);
  const id=random(),token=random(),m={name:String(d.name||'인쇄 노트북').replace(/[\x00-\x1f]/g,'').slice(0,60),tokenHash:await hash(token),expiresAt:now+30*86400000,lastSeen:0,printers:[]};await b.put(key(id),JSON.stringify(m),opts(m));return reply({id,token});
 }
 if(path==='/devices'&&req.method==='GET'){
  if(!loggedIn)return reply({error:'로그인이 필요합니다.'},401);const devices=[];let cursor;do{const page=await b.list({prefix:'_print_devices/',limit:1000,cursor});for(const item of page.objects){if(!/^_print_devices\/[a-f0-9]{48}$/.test(item.key))continue;const o=await b.get(item.key);if(!o)continue;const d=JSON.parse(await o.text());if(d.lastSeen>now-30000&&d.expiresAt>now){devices.push({id:item.key.split('/')[1],name:d.name,printers:d.printers});if((d.activeUntil||0)<now+25000)await b.put(item.key,JSON.stringify({...d,activeUntil:now+45000}),{...opts(d),onlyIf:{etagMatches:o.etag}});}}cursor=page.truncated?page.cursor:undefined;}while(cursor);return reply({devices});
 }
 if(path==='/submit'&&req.method==='POST'){
  if(!loggedIn)return reply({error:'로그인이 필요합니다.'},401);const d=await body(req);if(!/^[a-f0-9]{48}$/.test(d.album||'')||!/^[a-f0-9]{48}$/.test(d.device||'')||!Number.isInteger(d.copies)||d.copies<1||d.copies>10||!Number.isInteger(d.scale)||d.scale<85||d.scale>100||![0,90].includes(d.rotation))return reply({error:'인쇄 설정을 확인해 주세요.'},400);
  const device=await b.get(key(d.device));if(!device)return reply({error:'노트북 도우미가 연결되지 않았습니다.'},409);const machine=JSON.parse(await device.text());if(machine.expiresAt<=now||machine.lastSeen<now-30000||!machine.printers.some(p=>p.name===d.printer))return reply({error:'선택한 프린터가 연결되지 않았습니다.'},409);
  const k=d.album+'/meta',o=await b.get(k);if(!o)return reply({error:'사진이 없습니다.'},404);const m=JSON.parse(await o.text());if(!m.ready||!m.printRequested||m.expiresAt<=now)return reply({error:'사진이 없거나 만료됐습니다.'},404);if(['queued','printing'].includes(m.relayCommand?.state))return reply({error:'이미 프린터로 전달 중입니다.'},409);
  const command={id:random(),device:d.device,printer:d.printer,copies:d.copies,scale:d.scale,rotation:d.rotation,state:'queued',at:now};const next={...m,relayCommand:command,webPrintState:'queued'};if(!await b.put(k,JSON.stringify(next),{...opts(m),onlyIf:{etagMatches:o.etag}}))return reply({error:'다른 창에서 인쇄 요청이 진행 중입니다.'},409);return reply({ok:true});
 }
 const match=path.match(/^\/([a-f0-9]{48})\/(heartbeat|commands|claim|image|result)$/);if(!match)return reply({error:'없는 경로입니다.'},404);const [,id,action]=match,o=await b.get(key(id));if(!o)return reply({error:'도우미 연결이 만료되었습니다.'},401);const machine=JSON.parse(await o.text()),token=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!token||machine.expiresAt<=now||await hash(token)!==machine.tokenHash)return reply({error:'도우미 인증을 확인해 주세요.'},401);
 if(action==='heartbeat'&&req.method==='POST'){const d=await body(req);if(!Array.isArray(d.printers)||d.printers.length>32||d.printers.some(p=>typeof p.name!=='string'||!/^[a-zA-Z0-9_.-]{1,128}$/.test(p.name)))return reply({error:'프린터 정보를 확인해 주세요.'},400);const next={...machine,lastSeen:now,expiresAt:now+30*86400000,printers:d.printers.map(p=>({name:p.name,usb:p.usb===true}))};if(!await b.put(key(id),JSON.stringify(next),{...opts(next),onlyIf:{etagMatches:o.etag}})){const latest=JSON.parse(await(await b.get(key(id))).text());next.activeUntil=latest.activeUntil||0;await b.put(key(id),JSON.stringify(next),opts(next));}return reply({ok:true,active:(next.activeUntil||0)>now});}
 if(action==='commands'&&req.method==='GET'&&(machine.activeUntil||0)<=now)return reply({commands:[]});
 if(action==='commands'&&req.method==='GET')return reply({commands:(await albums(b)).filter(r=>r.meta.ready&&r.meta.expiresAt>now&&r.meta.relayCommand?.device===id&&['queued','printing'].includes(r.meta.relayCommand.state)).map(r=>({album:r.id,...r.meta.relayCommand}))});
 const input=action==='image'?{album:new URL(req.url).searchParams.get('album'),command:new URL(req.url).searchParams.get('command')}:await body(req);if(!/^[a-f0-9]{48}$/.test(input.album||''))return reply({error:'사진 정보가 없습니다.'},400);const k=input.album+'/meta',object=await b.get(k);if(!object)return reply({error:'사진이 없습니다.'},404);const m=JSON.parse(await object.text()),cmd=m.relayCommand;if(m.expiresAt<=now||!cmd||cmd.id!==input.command||cmd.device!==id)return reply({error:'이 도우미의 인쇄 요청이 아닙니다.'},403);
 if(action==='claim'&&req.method==='POST'){if(!['queued','printing'].includes(cmd.state))return reply({error:'이미 처리된 요청입니다.'},409);if(cmd.state==='queued'){const next={...m,webPrintState:'printing',relayCommand:{...cmd,state:'printing'}};if(!await b.put(k,JSON.stringify(next),{...opts(m),onlyIf:{etagMatches:object.etag}}))return reply({error:'접수 상태가 변경되었습니다.'},409);}return reply({ok:true});}
 if(action==='image'&&req.method==='GET'){const image=await b.get(input.album+'/'+(m.hasPrintFile?'9':'8'));if(!image)return reply({error:'사진이 없습니다.'},404);return new Response(image.body,{headers:{'Content-Type':image.httpMetadata.contentType,'Cache-Control':'no-store, private'}});}
 if(action==='result'&&req.method==='POST'){if(!['submitted','uncertain'].includes(input.state))return reply({error:'결과 상태를 확인해 주세요.'},400);await b.put(k,JSON.stringify({...m,relayCommand:{...cmd,state:input.state},webPrintState:m.webPrintState==='printed'?'printed':input.state}),opts(m));return reply({ok:true});}
 return reply({error:'지원하지 않는 요청입니다.'},405);
 }catch{return reply({error:'인쇄 연결 요청을 처리하지 못했습니다.'},400);}
}
