from pathlib import Path
import json
root=Path(__file__).resolve().parents[1];out=root/'deliverables/frame-guide-P';out.mkdir(parents=True,exist_ok=True)
layouts={}
for n in [2,4,6]:
 cols=1 if n==2 else 2;rows=n//cols;w=(1104-(cols-1)*24)//cols;h=(1320-(rows-1)*24)//rows
 slots=[[48+(i%cols)*(w+24),48+(i//cols)*(h+24),w,h] for i in range(n)];layouts[str(n)]=slots
 path='M0 0H1200V1776H0Z '+ ' '.join(f'M{x} {y}h{w}v{h}h-{w}Z' for x,y,w,h in slots)
 svg=f'<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1776" viewBox="0 0 1200 1776"><path fill="#e9efdf" fill-rule="evenodd" d="{path}"/></svg>'
 (out/f'upload-{n}cut.svg').write_text(svg)
 cards=[]
 for i,(x,y,w,h) in enumerate(slots):cards.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="8" fill="#fff" stroke="#769385" stroke-width="5"/><text x="{x+w/2}" y="{y+h/2}" text-anchor="middle" font-size="55" fill="#264d41">{i+1}</text>')
 diagram=f'<svg viewBox="0 0 1200 1776"><rect width="1200" height="1776" fill="#e9efdf"/>{"".join(cards)}<rect x="992" y="1568" width="160" height="160" fill="#d7cdf3"/><text x="1072" y="1639" text-anchor="middle" font-size="32">QR</text><text x="1072" y="1685" text-anchor="middle" font-size="26">비워두기</text><text x="480" y="1540" text-anchor="middle" font-size="45" fill="#426153">로고 · 장식 영역</text></svg>'
 table=''.join(f'<tr><td>{i+1}</td><td>{x}, {y}</td><td>{w} × {h}</td></tr>' for i,(x,y,w,h) in enumerate(slots))
 cards_html=f'<article><h2>{n}컷 <small>{cols}열 × {rows}행</small></h2>{diagram}<p class="size">사진 한 칸 <strong>{w} × {h}px</strong></p><table><tr><th>컷</th><th>시작점 X, Y</th><th>가로 × 세로</th></tr>{table}</table></article>'
 layouts[str(n)]={'slots':slots,'html':cards_html}
html='''<!doctype html><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#faf8f2;color:#26392f;font-family:'Apple SD Gothic Neo',Arial,sans-serif}main{width:1800px;padding:70px 70px 50px}header{border-bottom:3px solid #234b3c;padding-bottom:30px}.eyebrow{font-size:22px;letter-spacing:3px;color:#657d6d}h1{font-size:64px;margin:15px 0}header p{font-size:28px;line-height:1.6;margin:0}.spec{display:flex;gap:24px;margin:30px 0}.spec div{flex:1;background:#e9efdf;padding:22px 26px;border-radius:18px;font-size:25px}.spec strong{display:block;font-size:36px;margin-top:8px}.cards{display:flex;gap:24px}article{flex:1;min-width:0;padding:25px;background:#fff;border:1px solid #dce2d7;border-radius:22px}h2{font-size:36px;margin:0 0 20px}small{font-size:23px;font-weight:400;color:#748075;margin-left:15px}article svg{display:block;width:100%;height:630px}table{width:100%;border-collapse:collapse;font-size:22px;text-align:left}td,th{padding:12px 6px;border-bottom:1px solid #e6e9e4}th{font-size:19px;color:#69776d}.size{font-size:23px;margin:22px 0 10px}.notes{margin-top:30px;padding:26px 30px;background:#efe9fa;border-radius:18px;font-size:26px;line-height:1.65}.notes strong{color:#493b70}footer{font-size:19px;color:#637468;margin-top:25px;line-height:1.6}p{word-break:keep-all}</style><main><header><div class="eyebrow">YONSEI STUDIO · FRAME MAKING GUIDE · 2026.09.26</div><h1>프레임 제작 가이드</h1><p>Illustrator에서 제작 → 투명 PNG로 내보내기<br>SELPHY P 용지의 절취 후 크기에 맞춘 공통 규격입니다.</p></header><section class="spec"><div>작업 아트보드<strong>1200 × 1776px</strong></div><div>절취 후 완성 크기<strong>100 × 148mm</strong></div><div>컬러 · 출력 파일<strong>RGB / sRGB · PNG</strong></div></section><section class="cards">'''+''.join(layouts[str(n)]['html'] for n in [2,4,6])+'''</section><section class="notes"><strong>사진 영역은 흰색이 아니라 ‘투명’으로 뚫어 주세요.</strong><br>좌표 기준: 아트보드 왼쪽 위 (0, 0) · 단위: px · 사진 사이 간격: 24px<br>QR 자리: X 992 / Y 1568 / 160 × 160px — 배경만 두고 글자·인물·장식은 피해주세요.<br>QR은 앱이 넣습니다. 중요한 요소는 가장자리에서 36px(3mm) 이상 안쪽에 두세요.</section><footer><strong>내보내기:</strong> 아트보드 사용 · 배경 투명 · 1× / 화면용 72ppi → 실제 파일이 1200 × 1776px인지 확인<br><strong>용지:</strong> 절취 전 100 × 177mm → 출력 후 절취선을 따라 떼면 100 × 148mm. 절취 탭은 디자인에 포함하지 않습니다.<br>100 × 148mm 출력 시 약 305ppi입니다. 300ppi로 재확대하지 마세요. 무테 출력의 잘림은 실물 시험 인쇄로 확인하세요.<br>표준 업로드용 2·4·6컷 기준. 함께찍기 등 별도 배치는 해당 프레임의 좌표를 사용합니다.<br>규격 출처: Canon SELPHY CP1500 공식 설명서 / Specifications · cam.start.canon</footer></main>'''
(out/'frame-guide.html').write_text(html)
(out/'layouts.json').write_text(json.dumps({n:dict(width=1200,height=1776,slots=d['slots']) for n,d in layouts.items()},ensure_ascii=False,indent=2))
